language: cpp
dist: trusty
sudo: required

env:
  global:
   - SDL_VIDEODRIVER: dummy

matrix:
  include:

    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE='Debug'

    # Linux C++14 Clang builds
    - os: linux
      compiler: clang
      addons: &clang5
        apt:
          sources: ['llvm-toolchain-trusty-5.0', 'ubuntu-toolchain-r-test']
          packages: ['clang-5.0']
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" BUILD_TYPE='Release' SUPPORT=libstdc++-4.9-dev

    - os: linux
      compiler: clang
      addons: *clang5
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0" BUILD_TYPE='Debug' SUPPORT=libstdc++-4.9-dev

    # OSX C++14 Clang Builds

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE='Debug'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE='Release'

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then . .travis.linux; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then . .travis.osx; fi


before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Wdev
  - cd Build
